// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { almoxarifadosCreateAlmoxarifadoData, almoxarifadosCreateAlmoxarifadoErrors, almoxarifadosCreateAlmoxarifadoResponses, almoxarifadosListAlmoxarifadosData, almoxarifadosListAlmoxarifadosErrors, almoxarifadosListAlmoxarifadosResponses, contratosCreateContratoData, contratosCreateContratoErrors, contratosCreateContratoResponses, contratosListContratosData, contratosListContratosErrors, contratosListContratosResponses, contratosPrevisaoConsumoContratosData, contratosPrevisaoConsumoContratosResponses, fornecedoresCreateFornecedorData, fornecedoresCreateFornecedorErrors, fornecedoresCreateFornecedorResponses, fornecedoresGetFornecedorData, fornecedoresGetFornecedorErrors, fornecedoresGetFornecedorResponses, fornecedoresListFornecedoresData, fornecedoresListFornecedoresErrors, fornecedoresListFornecedoresResponses, healthCheckData, healthCheckResponses, licitaçõesCreateLicitacaoData, licitaçõesCreateLicitacaoErrors, licitaçõesCreateLicitacaoResponses, licitaçõesListLicitacoesData, licitaçõesListLicitacoesErrors, licitaçõesListLicitacoesResponses, loginLoginAccessTokenData, loginLoginAccessTokenErrors, loginLoginAccessTokenResponses, movimentaçõesListMovimentacoesData, movimentaçõesListMovimentacoesErrors, movimentaçõesListMovimentacoesResponses, notasFiscaisBaixarNotaFiscalData, notasFiscaisBaixarNotaFiscalErrors, notasFiscaisBaixarNotaFiscalResponses, notasFiscaisImportarNotaFiscalData, notasFiscaisImportarNotaFiscalErrors, notasFiscaisImportarNotaFiscalResponses, notasFiscaisListNotasFiscaisData, notasFiscaisListNotasFiscaisErrors, notasFiscaisListNotasFiscaisResponses, notasFiscaisParseXmlEndpointData, notasFiscaisParseXmlEndpointErrors, notasFiscaisParseXmlEndpointResponses, usersReadUserMeData, usersReadUserMeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class FornecedoresService {
    /**
     * List Fornecedores
     */
    public static listFornecedores<ThrowOnError extends boolean = true>(options?: Options<fornecedoresListFornecedoresData, ThrowOnError>) {
        return (options?.client ?? client).get<fornecedoresListFornecedoresResponses, fornecedoresListFornecedoresErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/fornecedores/',
            ...options
        });
    }
    
    /**
     * Create Fornecedor
     */
    public static createFornecedor<ThrowOnError extends boolean = true>(options: Options<fornecedoresCreateFornecedorData, ThrowOnError>) {
        return (options.client ?? client).post<fornecedoresCreateFornecedorResponses, fornecedoresCreateFornecedorErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/fornecedores/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get Fornecedor
     */
    public static getFornecedor<ThrowOnError extends boolean = true>(options: Options<fornecedoresGetFornecedorData, ThrowOnError>) {
        return (options.client ?? client).get<fornecedoresGetFornecedorResponses, fornecedoresGetFornecedorErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/fornecedores/{fornecedor_id}',
            ...options
        });
    }
}

export class LicitaçõesService {
    /**
     * List Licitacoes
     */
    public static listLicitacoes<ThrowOnError extends boolean = true>(options?: Options<licitaçõesListLicitacoesData, ThrowOnError>) {
        return (options?.client ?? client).get<licitaçõesListLicitacoesResponses, licitaçõesListLicitacoesErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/licitacoes/',
            ...options
        });
    }
    
    /**
     * Create Licitacao
     */
    public static createLicitacao<ThrowOnError extends boolean = true>(options: Options<licitaçõesCreateLicitacaoData, ThrowOnError>) {
        return (options.client ?? client).post<licitaçõesCreateLicitacaoResponses, licitaçõesCreateLicitacaoErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/licitacoes/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ContratosService {
    /**
     * List Contratos
     */
    public static listContratos<ThrowOnError extends boolean = true>(options?: Options<contratosListContratosData, ThrowOnError>) {
        return (options?.client ?? client).get<contratosListContratosResponses, contratosListContratosErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/contratos/',
            ...options
        });
    }
    
    /**
     * Create Contrato
     */
    public static createContrato<ThrowOnError extends boolean = true>(options: Options<contratosCreateContratoData, ThrowOnError>) {
        return (options.client ?? client).post<contratosCreateContratoResponses, contratosCreateContratoErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/contratos/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Previsao Consumo Contratos
     */
    public static previsaoConsumoContratos<ThrowOnError extends boolean = true>(options?: Options<contratosPrevisaoConsumoContratosData, ThrowOnError>) {
        return (options?.client ?? client).get<contratosPrevisaoConsumoContratosResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/contratos/previsao-consumo',
            ...options
        });
    }
}

export class NotasFiscaisService {
    /**
     * List Notas Fiscais
     */
    public static listNotasFiscais<ThrowOnError extends boolean = true>(options?: Options<notasFiscaisListNotasFiscaisData, ThrowOnError>) {
        return (options?.client ?? client).get<notasFiscaisListNotasFiscaisResponses, notasFiscaisListNotasFiscaisErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/notas-fiscais/',
            ...options
        });
    }
    
    /**
     * Importar Nota Fiscal
     */
    public static importarNotaFiscal<ThrowOnError extends boolean = true>(options: Options<notasFiscaisImportarNotaFiscalData, ThrowOnError>) {
        return (options.client ?? client).post<notasFiscaisImportarNotaFiscalResponses, notasFiscaisImportarNotaFiscalErrors, ThrowOnError>({
            ...formDataBodySerializer,
            responseType: 'json',
            url: '/api/v1/notas-fiscais/importar',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
    
    /**
     * Baixar Nota Fiscal
     *
     * Efetua a baixa da nota fiscal, deduzindo os itens do contrato e gerando as movimentações.
     * Operação 100% transacional ACID (Tudo ou Nada).
     */
    public static baixarNotaFiscal<ThrowOnError extends boolean = true>(options: Options<notasFiscaisBaixarNotaFiscalData, ThrowOnError>) {
        return (options.client ?? client).post<notasFiscaisBaixarNotaFiscalResponses, notasFiscaisBaixarNotaFiscalErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/notas-fiscais/{nf_id}/baixar',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Parse Xml Endpoint
     *
     * Recebe um arquivo XML de Nota Fiscal Eletrônica e retorna
     * os dados extraídos estruturados para preenchimento no frontend.
     */
    public static parseXmlEndpoint<ThrowOnError extends boolean = true>(options: Options<notasFiscaisParseXmlEndpointData, ThrowOnError>) {
        return (options.client ?? client).post<notasFiscaisParseXmlEndpointResponses, notasFiscaisParseXmlEndpointErrors, ThrowOnError>({
            ...formDataBodySerializer,
            responseType: 'json',
            url: '/api/v1/notas-fiscais/parse-xml',
            ...options,
            headers: {
                'Content-Type': null,
                ...options.headers
            }
        });
    }
}

export class MovimentaçõesService {
    /**
     * List Movimentacoes
     */
    public static listMovimentacoes<ThrowOnError extends boolean = true>(options?: Options<movimentaçõesListMovimentacoesData, ThrowOnError>) {
        return (options?.client ?? client).get<movimentaçõesListMovimentacoesResponses, movimentaçõesListMovimentacoesErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/movimentacoes/',
            ...options
        });
    }
}

export class AlmoxarifadosService {
    /**
     * List Almoxarifados
     */
    public static listAlmoxarifados<ThrowOnError extends boolean = true>(options?: Options<almoxarifadosListAlmoxarifadosData, ThrowOnError>) {
        return (options?.client ?? client).get<almoxarifadosListAlmoxarifadosResponses, almoxarifadosListAlmoxarifadosErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/almoxarifados/',
            ...options
        });
    }
    
    /**
     * Create Almoxarifado
     */
    public static createAlmoxarifado<ThrowOnError extends boolean = true>(options: Options<almoxarifadosCreateAlmoxarifadoData, ThrowOnError>) {
        return (options.client ?? client).post<almoxarifadosCreateAlmoxarifadoResponses, almoxarifadosCreateAlmoxarifadoErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/almoxarifados/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     *
     * OAuth2 compatible token login, get an access token for future requests
     */
    public static loginAccessToken<ThrowOnError extends boolean = true>(options: Options<loginLoginAccessTokenData, ThrowOnError>) {
        return (options.client ?? client).post<loginLoginAccessTokenResponses, loginLoginAccessTokenErrors, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            responseType: 'json',
            url: '/login/access-token',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options.headers
            }
        });
    }

    public static recoverPassword(_options?: unknown) {
        return Promise.reject(new Error("Recuperação de senha não está disponível nesta API"));
    }

    public static resetPassword(_options?: unknown) {
        return Promise.reject(new Error("Redefinição de senha não está disponível nesta API"));
    }
}

export class UsersService {
    /**
     * Read User Me
     *
     * Get current user.
     */
    public static readUserMe<ThrowOnError extends boolean = true>(options?: Options<usersReadUserMeData, ThrowOnError>) {
        return (options?.client ?? client).get<usersReadUserMeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/users/me',
            ...options
        });
    }

    public static registerUser(_options?: unknown) {
        return Promise.reject(new Error("Cadastro público não está disponível nesta API"));
    }

    public static readUsers(_options?: unknown) {
        return Promise.reject(new Error("Listagem de usuários não está disponível nesta API"));
    }

    public static createUser(_options?: unknown) {
        return Promise.reject(new Error("Criação de usuário não está disponível nesta API"));
    }

    public static updateUser(_options?: unknown) {
        return Promise.reject(new Error("Atualização de usuário não está disponível nesta API"));
    }

    public static deleteUser(_options?: unknown) {
        return Promise.reject(new Error("Exclusão de usuário não está disponível nesta API"));
    }

    public static updateUserMe(_options?: unknown) {
        return Promise.reject(new Error("Atualização de perfil não está disponível nesta API"));
    }

    public static deleteUserMe(_options?: unknown) {
        return Promise.reject(new Error("Exclusão de conta não está disponível nesta API"));
    }

    public static updatePasswordMe(_options?: unknown) {
        return Promise.reject(new Error("Troca de senha não está disponível nesta API"));
    }
}

export class DefaultService {
    /**
     * Health Check
     */
    public static healthCheck<ThrowOnError extends boolean = true>(options?: Options<healthCheckData, ThrowOnError>) {
        return (options?.client ?? client).get<healthCheckResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/health',
            ...options
        });
    }
}
