// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AlmoxarifadoCreate
 */
export type AlmoxarifadoCreate = {
    /**
     * Nome
     */
    nome: string;
    /**
     * Localizacao
     */
    localizacao?: string | null;
    /**
     * Ativo
     */
    ativo?: boolean;
};

/**
 * AlmoxarifadoOut
 */
export type AlmoxarifadoOut = {
    /**
     * Nome
     */
    nome: string;
    /**
     * Localizacao
     */
    localizacao?: string | null;
    /**
     * Ativo
     */
    ativo?: boolean;
    /**
     * Id
     */
    id: number;
};

/**
 * BaixaRequest
 */
export type BaixaRequest = {
    /**
     * Justificativa
     */
    justificativa?: string | null;
    /**
     * Usuario Id
     */
    usuario_id: number;
    /**
     * Almoxarifado Id
     */
    almoxarifado_id?: number | null;
};

/**
 * Body_Notas Fiscais-importar_nota_fiscal
 */
export type Body_Notas_Fiscais_importar_nota_fiscal = {
    /**
     * Arquivo Pdf
     */
    arquivo_pdf: Blob | File;
    /**
     * Nota Fiscal Data
     *
     * JSON contendo os dados da NotaFiscalCreate e um array 'itens' com ItemNotaFiscalCreate
     */
    nota_fiscal_data: string;
};

/**
 * Body_Notas Fiscais-parse_xml_endpoint
 */
export type Body_Notas_Fiscais_parse_xml_endpoint = {
    /**
     * Arquivo Xml
     */
    arquivo_xml: Blob | File;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ContratoCreate
 */
export type ContratoCreate = {
    /**
     * Licitacao Id
     */
    licitacao_id: number;
    /**
     * Fornecedor Id
     */
    fornecedor_id: number;
    /**
     * Numero
     */
    numero: string;
    /**
     * Ano
     */
    ano: number;
    /**
     * Data Inicio
     */
    data_inicio?: string | null;
    /**
     * Data Fim
     */
    data_fim?: string | null;
    /**
     * Valor Total
     */
    valor_total: number;
    /**
     * Situacao
     */
    situacao: string;
};

/**
 * ContratoDetalhadoOut
 */
export type ContratoDetalhadoOut = {
    /**
     * Licitacao Id
     */
    licitacao_id: number;
    /**
     * Fornecedor Id
     */
    fornecedor_id: number;
    /**
     * Numero
     */
    numero: string;
    /**
     * Ano
     */
    ano: number;
    /**
     * Data Inicio
     */
    data_inicio?: string | null;
    /**
     * Data Fim
     */
    data_fim?: string | null;
    /**
     * Valor Total
     */
    valor_total: number;
    /**
     * Situacao
     */
    situacao: string;
    /**
     * Id
     */
    id: number;
    fornecedor?: FornecedorOut | null;
    /**
     * Itens
     */
    itens?: Array<ItemContratoOut>;
};

/**
 * ContratoOut
 */
export type ContratoOut = {
    /**
     * Licitacao Id
     */
    licitacao_id: number;
    /**
     * Fornecedor Id
     */
    fornecedor_id: number;
    /**
     * Numero
     */
    numero: string;
    /**
     * Ano
     */
    ano: number;
    /**
     * Data Inicio
     */
    data_inicio?: string | null;
    /**
     * Data Fim
     */
    data_fim?: string | null;
    /**
     * Valor Total
     */
    valor_total: number;
    /**
     * Situacao
     */
    situacao: string;
    /**
     * Id
     */
    id: number;
};

/**
 * FornecedorCreate
 */
export type FornecedorCreate = {
    /**
     * Razao Social
     */
    razao_social: string;
    /**
     * Nome Fantasia
     */
    nome_fantasia?: string | null;
    /**
     * Cnpj
     */
    cnpj: string;
    /**
     * Inscricao Estadual
     */
    inscricao_estadual?: string | null;
    /**
     * Endereco
     */
    endereco?: string | null;
    /**
     * Cidade
     */
    cidade?: string | null;
    /**
     * Estado
     */
    estado?: string | null;
    /**
     * Telefone
     */
    telefone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Ativo
     */
    ativo?: boolean;
};

/**
 * FornecedorOut
 */
export type FornecedorOut = {
    /**
     * Razao Social
     */
    razao_social: string;
    /**
     * Nome Fantasia
     */
    nome_fantasia?: string | null;
    /**
     * Cnpj
     */
    cnpj: string;
    /**
     * Inscricao Estadual
     */
    inscricao_estadual?: string | null;
    /**
     * Endereco
     */
    endereco?: string | null;
    /**
     * Cidade
     */
    cidade?: string | null;
    /**
     * Estado
     */
    estado?: string | null;
    /**
     * Telefone
     */
    telefone?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Ativo
     */
    ativo?: boolean;
    /**
     * Id
     */
    id: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemContratoOut
 */
export type ItemContratoOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Contrato Id
     */
    contrato_id: number;
    /**
     * Numero Item
     */
    numero_item: number;
    /**
     * Codigo
     */
    codigo?: string | null;
    /**
     * Descricao
     */
    descricao: string;
    /**
     * Unidade
     */
    unidade: string;
    /**
     * Quantidade Contratada
     */
    quantidade_contratada: number;
    /**
     * Valor Unitario
     */
    valor_unitario: number;
    /**
     * Saldo Atual
     */
    saldo_atual: number;
};

/**
 * ItemNotaFiscalOut
 */
export type ItemNotaFiscalOut = {
    /**
     * Codigo
     */
    codigo?: string | null;
    /**
     * Descricao
     */
    descricao: string;
    /**
     * Quantidade
     */
    quantidade: number;
    /**
     * Unidade
     */
    unidade: string;
    /**
     * Valor Unitario
     */
    valor_unitario: number;
    /**
     * Item Contrato Id
     */
    item_contrato_id?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Nota Fiscal Id
     */
    nota_fiscal_id: number;
    /**
     * Percentual Confianca
     */
    percentual_confianca?: number | null;
    /**
     * Status Identificacao
     */
    status_identificacao?: string | null;
};

/**
 * LicitacaoCreate
 */
export type LicitacaoCreate = {
    /**
     * Numero
     */
    numero: string;
    /**
     * Ano
     */
    ano: number;
    /**
     * Modalidade
     */
    modalidade: string;
    /**
     * Processo
     */
    processo?: string | null;
    /**
     * Objeto
     */
    objeto: string;
    /**
     * Data
     */
    data?: string | null;
    /**
     * Situacao
     */
    situacao: string;
};

/**
 * LicitacaoOut
 */
export type LicitacaoOut = {
    /**
     * Numero
     */
    numero: string;
    /**
     * Ano
     */
    ano: number;
    /**
     * Modalidade
     */
    modalidade: string;
    /**
     * Processo
     */
    processo?: string | null;
    /**
     * Objeto
     */
    objeto: string;
    /**
     * Data
     */
    data?: string | null;
    /**
     * Situacao
     */
    situacao: string;
    /**
     * Id
     */
    id: number;
};

/**
 * MovimentacaoOut
 */
export type MovimentacaoOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Nota Fiscal Id
     */
    nota_fiscal_id?: number | null;
    /**
     * Item Contrato Id
     */
    item_contrato_id: number;
    /**
     * Tipo Movimento
     */
    tipo_movimento: string;
    /**
     * Quantidade
     */
    quantidade: number;
    /**
     * Saldo Anterior
     */
    saldo_anterior: number;
    /**
     * Saldo Posterior
     */
    saldo_posterior: number;
    /**
     * Almoxarifado Id
     */
    almoxarifado_id?: number | null;
    /**
     * Usuario Id
     */
    usuario_id: number;
    /**
     * Data Hora
     */
    data_hora: string;
    /**
     * Justificativa
     */
    justificativa: string;
};

/**
 * NotaFiscalOut
 */
export type NotaFiscalOut = {
    /**
     * Contrato Id
     */
    contrato_id: number;
    /**
     * Fornecedor Id
     */
    fornecedor_id: number;
    /**
     * Numero
     */
    numero: string;
    /**
     * Serie
     */
    serie?: string | null;
    /**
     * Chave Acesso
     */
    chave_acesso?: string | null;
    /**
     * Data Emissao
     */
    data_emissao?: string | null;
    /**
     * Valor Total
     */
    valor_total?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Arquivo Pdf Path
     */
    arquivo_pdf_path?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Criado Em
     */
    criado_em: string;
    /**
     * Itens
     */
    itens?: Array<ItemNotaFiscalOut>;
};

/**
 * PrevisaoConsumoOut
 */
export type PrevisaoConsumoOut = {
    /**
     * Contrato Id
     */
    contrato_id: number;
    /**
     * Contrato Numero
     */
    contrato_numero: string;
    /**
     * Fornecedor Id
     */
    fornecedor_id: number;
    /**
     * Item Id
     */
    item_id: number;
    /**
     * Item Descricao
     */
    item_descricao: string;
    /**
     * Saldo Atual
     */
    saldo_atual: number;
    /**
     * Total Baixado
     */
    total_baixado: number;
    /**
     * Taxa Diaria
     */
    taxa_diaria: number;
    /**
     * Dias Restantes
     */
    dias_restantes?: number | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Perfil (ADMIN ou OPERADOR)
     */
    perfil?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type fornecedoresListFornecedoresData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/fornecedores/';
};

export type fornecedoresListFornecedoresErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type fornecedoresListFornecedoresError = fornecedoresListFornecedoresErrors[keyof fornecedoresListFornecedoresErrors];

export type fornecedoresListFornecedoresResponses = {
    /**
     * Response Fornecedores-List Fornecedores
     *
     * Successful Response
     */
    200: Array<FornecedorOut>;
};

export type fornecedoresListFornecedoresResponse = fornecedoresListFornecedoresResponses[keyof fornecedoresListFornecedoresResponses];

export type fornecedoresCreateFornecedorData = {
    body: FornecedorCreate;
    path?: never;
    query?: never;
    url: '/api/v1/fornecedores/';
};

export type fornecedoresCreateFornecedorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type fornecedoresCreateFornecedorError = fornecedoresCreateFornecedorErrors[keyof fornecedoresCreateFornecedorErrors];

export type fornecedoresCreateFornecedorResponses = {
    /**
     * Successful Response
     */
    200: FornecedorOut;
};

export type fornecedoresCreateFornecedorResponse = fornecedoresCreateFornecedorResponses[keyof fornecedoresCreateFornecedorResponses];

export type fornecedoresGetFornecedorData = {
    body?: never;
    path: {
        /**
         * Fornecedor Id
         */
        fornecedor_id: number;
    };
    query?: never;
    url: '/api/v1/fornecedores/{fornecedor_id}';
};

export type fornecedoresGetFornecedorErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type fornecedoresGetFornecedorError = fornecedoresGetFornecedorErrors[keyof fornecedoresGetFornecedorErrors];

export type fornecedoresGetFornecedorResponses = {
    /**
     * Successful Response
     */
    200: FornecedorOut;
};

export type fornecedoresGetFornecedorResponse = fornecedoresGetFornecedorResponses[keyof fornecedoresGetFornecedorResponses];

export type licitaçõesListLicitacoesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/licitacoes/';
};

export type licitaçõesListLicitacoesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type licitaçõesListLicitacoesError = licitaçõesListLicitacoesErrors[keyof licitaçõesListLicitacoesErrors];

export type licitaçõesListLicitacoesResponses = {
    /**
     * Response Licitações-List Licitacoes
     *
     * Successful Response
     */
    200: Array<LicitacaoOut>;
};

export type licitaçõesListLicitacoesResponse = licitaçõesListLicitacoesResponses[keyof licitaçõesListLicitacoesResponses];

export type licitaçõesCreateLicitacaoData = {
    body: LicitacaoCreate;
    path?: never;
    query?: never;
    url: '/api/v1/licitacoes/';
};

export type licitaçõesCreateLicitacaoErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type licitaçõesCreateLicitacaoError = licitaçõesCreateLicitacaoErrors[keyof licitaçõesCreateLicitacaoErrors];

export type licitaçõesCreateLicitacaoResponses = {
    /**
     * Successful Response
     */
    200: LicitacaoOut;
};

export type licitaçõesCreateLicitacaoResponse = licitaçõesCreateLicitacaoResponses[keyof licitaçõesCreateLicitacaoResponses];

export type contratosListContratosData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/contratos/';
};

export type contratosListContratosErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type contratosListContratosError = contratosListContratosErrors[keyof contratosListContratosErrors];

export type contratosListContratosResponses = {
    /**
     * Response Contratos-List Contratos
     *
     * Successful Response
     */
    200: Array<ContratoDetalhadoOut>;
};

export type contratosListContratosResponse = contratosListContratosResponses[keyof contratosListContratosResponses];

export type contratosCreateContratoData = {
    body: ContratoCreate;
    path?: never;
    query?: never;
    url: '/api/v1/contratos/';
};

export type contratosCreateContratoErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type contratosCreateContratoError = contratosCreateContratoErrors[keyof contratosCreateContratoErrors];

export type contratosCreateContratoResponses = {
    /**
     * Successful Response
     */
    200: ContratoOut;
};

export type contratosCreateContratoResponse = contratosCreateContratoResponses[keyof contratosCreateContratoResponses];

export type contratosPrevisaoConsumoContratosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/contratos/previsao-consumo';
};

export type contratosPrevisaoConsumoContratosResponses = {
    /**
     * Response Contratos-Previsao Consumo Contratos
     *
     * Successful Response
     */
    200: Array<PrevisaoConsumoOut>;
};

export type contratosPrevisaoConsumoContratosResponse = contratosPrevisaoConsumoContratosResponses[keyof contratosPrevisaoConsumoContratosResponses];

export type notasFiscaisListNotasFiscaisData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/notas-fiscais/';
};

export type notasFiscaisListNotasFiscaisErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type notasFiscaisListNotasFiscaisError = notasFiscaisListNotasFiscaisErrors[keyof notasFiscaisListNotasFiscaisErrors];

export type notasFiscaisListNotasFiscaisResponses = {
    /**
     * Response Notas Fiscais-List Notas Fiscais
     *
     * Successful Response
     */
    200: Array<NotaFiscalOut>;
};

export type notasFiscaisListNotasFiscaisResponse = notasFiscaisListNotasFiscaisResponses[keyof notasFiscaisListNotasFiscaisResponses];

export type notasFiscaisImportarNotaFiscalData = {
    body: Body_Notas_Fiscais_importar_nota_fiscal;
    path?: never;
    query?: never;
    url: '/api/v1/notas-fiscais/importar';
};

export type notasFiscaisImportarNotaFiscalErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type notasFiscaisImportarNotaFiscalError = notasFiscaisImportarNotaFiscalErrors[keyof notasFiscaisImportarNotaFiscalErrors];

export type notasFiscaisImportarNotaFiscalResponses = {
    /**
     * Successful Response
     */
    200: NotaFiscalOut;
};

export type notasFiscaisImportarNotaFiscalResponse = notasFiscaisImportarNotaFiscalResponses[keyof notasFiscaisImportarNotaFiscalResponses];

export type notasFiscaisBaixarNotaFiscalData = {
    body: BaixaRequest;
    path: {
        /**
         * Nf Id
         */
        nf_id: number;
    };
    query?: never;
    url: '/api/v1/notas-fiscais/{nf_id}/baixar';
};

export type notasFiscaisBaixarNotaFiscalErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type notasFiscaisBaixarNotaFiscalError = notasFiscaisBaixarNotaFiscalErrors[keyof notasFiscaisBaixarNotaFiscalErrors];

export type notasFiscaisBaixarNotaFiscalResponses = {
    /**
     * Response Notas Fiscais-Baixar Nota Fiscal
     *
     * Successful Response
     */
    200: Array<MovimentacaoOut>;
};

export type notasFiscaisBaixarNotaFiscalResponse = notasFiscaisBaixarNotaFiscalResponses[keyof notasFiscaisBaixarNotaFiscalResponses];

export type notasFiscaisParseXmlEndpointData = {
    body: Body_Notas_Fiscais_parse_xml_endpoint;
    path?: never;
    query?: never;
    url: '/api/v1/notas-fiscais/parse-xml';
};

export type notasFiscaisParseXmlEndpointErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type notasFiscaisParseXmlEndpointError = notasFiscaisParseXmlEndpointErrors[keyof notasFiscaisParseXmlEndpointErrors];

export type notasFiscaisParseXmlEndpointResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type movimentaçõesListMovimentacoesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/movimentacoes/';
};

export type movimentaçõesListMovimentacoesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type movimentaçõesListMovimentacoesError = movimentaçõesListMovimentacoesErrors[keyof movimentaçõesListMovimentacoesErrors];

export type movimentaçõesListMovimentacoesResponses = {
    /**
     * Response Movimentações-List Movimentacoes
     *
     * Successful Response
     */
    200: Array<MovimentacaoOut>;
};

export type movimentaçõesListMovimentacoesResponse = movimentaçõesListMovimentacoesResponses[keyof movimentaçõesListMovimentacoesResponses];

export type almoxarifadosListAlmoxarifadosData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/almoxarifados/';
};

export type almoxarifadosListAlmoxarifadosErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type almoxarifadosListAlmoxarifadosError = almoxarifadosListAlmoxarifadosErrors[keyof almoxarifadosListAlmoxarifadosErrors];

export type almoxarifadosListAlmoxarifadosResponses = {
    /**
     * Response Almoxarifados-List Almoxarifados
     *
     * Successful Response
     */
    200: Array<AlmoxarifadoOut>;
};

export type almoxarifadosListAlmoxarifadosResponse = almoxarifadosListAlmoxarifadosResponses[keyof almoxarifadosListAlmoxarifadosResponses];

export type almoxarifadosCreateAlmoxarifadoData = {
    body: AlmoxarifadoCreate;
    path?: never;
    query?: never;
    url: '/api/v1/almoxarifados/';
};

export type almoxarifadosCreateAlmoxarifadoErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type almoxarifadosCreateAlmoxarifadoError = almoxarifadosCreateAlmoxarifadoErrors[keyof almoxarifadosCreateAlmoxarifadoErrors];

export type almoxarifadosCreateAlmoxarifadoResponses = {
    /**
     * Successful Response
     */
    200: AlmoxarifadoOut;
};

export type almoxarifadosCreateAlmoxarifadoResponse = almoxarifadosCreateAlmoxarifadoResponses[keyof almoxarifadosCreateAlmoxarifadoResponses];

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type healthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type healthCheckResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
