"""Add Almoxarifado

Revision ID: 10fc08d3c4cc
Revises: 61c4feb9d77a
Create Date: 2026-08-15 10:17:05.435589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fc08d3c4cc'
down_revision: Union[str, None] = '61c4feb9d77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almoxarifados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('localizacao', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_almoxarifados_id'), 'almoxarifados', ['id'], unique=False)
    op.create_table('estoque_almoxarifados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_contrato_id', sa.Integer(), nullable=False),
    sa.Column('almoxarifado_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['almoxarifado_id'], ['almoxarifados.id'], ),
    sa.ForeignKeyConstraint(['item_contrato_id'], ['itens_contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_almoxarifados_id'), 'estoque_almoxarifados', ['id'], unique=False)
    op.add_column('movimentacoes', sa.Column('almoxarifado_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movimentacoes', 'almoxarifados', ['almoxarifado_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimentacoes', type_='foreignkey')
    op.drop_column('movimentacoes', 'almoxarifado_id')
    op.drop_index(op.f('ix_estoque_almoxarifados_id'), table_name='estoque_almoxarifados')
    op.drop_table('estoque_almoxarifados')
    op.drop_index(op.f('ix_almoxarifados_id'), table_name='almoxarifados')
    op.drop_table('almoxarifados')
    # ### end Alembic commands ###
