"""Criacao Inicial do Banco

Revision ID: 61c4feb9d77a
Revises: 
Create Date: 2026-08-13 12:03:03.052273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c4feb9d77a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('inscricao_estadual', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=True)
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_table('licitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(), nullable=False),
    sa.Column('processo', sa.String(), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoes_id'), 'licitacoes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licitacao_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('situacao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('operacao', sa.String(), nullable=False),
    sa.Column('tabela', sa.String(), nullable=False),
    sa.Column('registro_id', sa.String(), nullable=False),
    sa.Column('dados_anteriores', sa.JSON(), nullable=True),
    sa.Column('dados_novos', sa.JSON(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_auditoria_id'), 'log_auditoria', ['id'], unique=False)
    op.create_table('itens_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('gtin', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('quantidade_contratada', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('saldo_atual', sa.Float(), nullable=False),
    sa.CheckConstraint('saldo_atual >= 0', name='check_saldo_positivo'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_contrato_id'), 'itens_contrato', ['id'], unique=False)
    op.create_table('notas_fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('serie', sa.String(), nullable=True),
    sa.Column('chave_acesso', sa.String(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('arquivo_pdf_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_fiscais_chave_acesso'), 'notas_fiscais', ['chave_acesso'], unique=True)
    op.create_index(op.f('ix_notas_fiscais_id'), 'notas_fiscais', ['id'], unique=False)
    op.create_table('itens_nota_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_fiscal_id', sa.Integer(), nullable=False),
    sa.Column('item_contrato_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('percentual_confianca', sa.Float(), nullable=True),
    sa.Column('status_identificacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_contrato_id'], ['itens_contrato.id'], ),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['notas_fiscais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_nota_fiscal_id'), 'itens_nota_fiscal', ['id'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_fiscal_id', sa.Integer(), nullable=True),
    sa.Column('item_contrato_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimento', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('saldo_anterior', sa.Float(), nullable=False),
    sa.Column('saldo_posterior', sa.Float(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_contrato_id'], ['itens_contrato.id'], ),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['notas_fiscais.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacoes_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_itens_nota_fiscal_id'), table_name='itens_nota_fiscal')
    op.drop_table('itens_nota_fiscal')
    op.drop_index(op.f('ix_notas_fiscais_id'), table_name='notas_fiscais')
    op.drop_index(op.f('ix_notas_fiscais_chave_acesso'), table_name='notas_fiscais')
    op.drop_table('notas_fiscais')
    op.drop_index(op.f('ix_itens_contrato_id'), table_name='itens_contrato')
    op.drop_table('itens_contrato')
    op.drop_index(op.f('ix_log_auditoria_id'), table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_licitacoes_id'), table_name='licitacoes')
    op.drop_table('licitacoes')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
