/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAlmoxarifadosRouteImport } from './routes/_layout/almoxarifados'
import { Route as LayoutContratosRouteImport } from './routes/_layout/contratos'
import { Route as LayoutFornecedoresRouteImport } from './routes/_layout/fornecedores'
import { Route as LayoutNotasFiscaisRouteImport } from './routes/_layout/notas-fiscais'
import { Route as LayoutRelatoriosRouteImport } from './routes/_layout/relatorios'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlmoxarifadosRoute = LayoutAlmoxarifadosRouteImport.update({
  id: '/almoxarifados',
  path: '/almoxarifados',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContratosRoute = LayoutContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFornecedoresRoute = LayoutFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotasFiscaisRoute = LayoutNotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRelatoriosRoute = LayoutRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/almoxarifados': typeof LayoutAlmoxarifadosRoute
  '/contratos': typeof LayoutContratosRoute
  '/fornecedores': typeof LayoutFornecedoresRoute
  '/notas-fiscais': typeof LayoutNotasFiscaisRoute
  '/relatorios': typeof LayoutRelatoriosRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/almoxarifados': typeof LayoutAlmoxarifadosRoute
  '/contratos': typeof LayoutContratosRoute
  '/fornecedores': typeof LayoutFornecedoresRoute
  '/notas-fiscais': typeof LayoutNotasFiscaisRoute
  '/relatorios': typeof LayoutRelatoriosRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/almoxarifados': typeof LayoutAlmoxarifadosRoute
  '/_layout/contratos': typeof LayoutContratosRoute
  '/_layout/fornecedores': typeof LayoutFornecedoresRoute
  '/_layout/notas-fiscais': typeof LayoutNotasFiscaisRoute
  '/_layout/relatorios': typeof LayoutRelatoriosRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/almoxarifados'
    | '/contratos'
    | '/fornecedores'
    | '/notas-fiscais'
    | '/relatorios'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/almoxarifados'
    | '/contratos'
    | '/fornecedores'
    | '/notas-fiscais'
    | '/relatorios'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/almoxarifados'
    | '/_layout/contratos'
    | '/_layout/fornecedores'
    | '/_layout/notas-fiscais'
    | '/_layout/relatorios'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/almoxarifados': {
      id: '/_layout/almoxarifados'
      path: '/almoxarifados'
      fullPath: '/almoxarifados'
      preLoaderRoute: typeof LayoutAlmoxarifadosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contratos': {
      id: '/_layout/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof LayoutContratosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fornecedores': {
      id: '/_layout/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof LayoutFornecedoresRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notas-fiscais': {
      id: '/_layout/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof LayoutNotasFiscaisRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/relatorios': {
      id: '/_layout/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof LayoutRelatoriosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAlmoxarifadosRoute: typeof LayoutAlmoxarifadosRoute
  LayoutContratosRoute: typeof LayoutContratosRoute
  LayoutFornecedoresRoute: typeof LayoutFornecedoresRoute
  LayoutNotasFiscaisRoute: typeof LayoutNotasFiscaisRoute
  LayoutRelatoriosRoute: typeof LayoutRelatoriosRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAlmoxarifadosRoute: LayoutAlmoxarifadosRoute,
  LayoutContratosRoute: LayoutContratosRoute,
  LayoutFornecedoresRoute: LayoutFornecedoresRoute,
  LayoutNotasFiscaisRoute: LayoutNotasFiscaisRoute,
  LayoutRelatoriosRoute: LayoutRelatoriosRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
