export const MODALIDADES_LICITACAO = [
  "Pregão eletrônico",
  "Pregão presencial",
  "Concorrência",
  "Concorrência eletrônica",
  "Concurso",
  "Leilão",
  "Diálogo competitivo",
  "Dispensa de licitação",
  "Inexigibilidade de licitação",
  "Credenciamento",
  "Pré-qualificação",
  "Chamada pública",
  "Registro de preços",
  "Adesão à ata de registro de preços",
  "Convite",
  "Tomada de preços",
  "RDC",
  "Contratação direta",
] as const
